### PR TITLE
Fix exact endpoint to query for setting node

### LINKED ISSUE #37: Bug in blnet_web.py
After having some issues with a UVR1611 not being node 1 I found out that there is most probably a bug in blnet_web.py

Line 166. In `def set_node(self, node):`

The http request changes the node number of the BLNET not the UVR1611.

 `self.ip + "/can.htm?blaA=" + str(node)`

should be changed to

`self.ip + "/can.htm?blaB=" + str(node)`

### PR DESCRIPTION
**Pull request by nielstron**
Fixes #37

### CODE REVIEW

**Comment by whatashit** [comment]
Hello Niels,

it has been a while since u created the pull request. Would it be possible to merge it or give my write access so that I can merge it?
Winter is coming and I would love to have more control of my heating system during this period with HA. Well unfortunaltely without that fix it doenst really work.

Thanks a lot!

**Comment by nielstron** [comment]
Hey @whatashit 
I am not sure why I did not merge this but it would seem to me that I didn't because I was unable to try if this actually fixes the issue. Are you able to verify this?

**Comment by nielstron** [comment]
Let's see if this fixes it for other users as well or whether we will need to figure out a different system for different blnets

**Comment by whatashit** [comment]
I will try asap. Hopefully tonight

**Pull request merged**
