### PR TITLE
Fix parser

### PR DESCRIPTION
**Pull request by zwotzie**
Hi Nils, this is a fix for not having values of:
- speed
- energy
- power

that's my setup at home.
thank you for your project

### CODE REVIEW

**Comment by nielstron** [comment]
Looks good, thank you for the proposed fix! Did you try this script at home/can you elaborate what needed to be fixed?

**Comment by zwotzie** [comment]
Yes you are understanding that correctly, in my setup there is nothing like speed/energy/power messurments. So in the data it is missing.

My old blnet is "ill" and do not function as it should anymore. So I decided to integrate the direct connection with your project and it doesn't work out of the box. This is the fix for it.

**Comment by zwotzie** [comment]
I also added a test for the parser, but it fails in py3.8 in Travis CI. Don't know why.

**Comment by nielstron** [comment]
I also don't see why 3.8 is failing, but it's unrelated to your change. Looks good to me :)

**Comment by zwotzie** [comment]
what I do not understand, that i have speed values (in php version) but did not get it here with BLNETDirect

**Pull request merged**
